ARG VARIANT="bullseye"
FROM buildpack-deps:${VARIANT}-curl

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=${USER_UID}
ARG WORKDIR="/home/${USERNAME}"

COPY common.sh /
RUN bash /common.sh "${USERNAME}" "${USER_UID}" "${USER_GID}" \
 && rm /common.sh

RUN wget -O- https://aka.ms/install-vscode-server/setup.sh | USER=root sh

COPY docker-entrypoint.sh /
RUN chmod +x /docker-entrypoint.sh

USER ${USERNAME}
WORKDIR ${WORKDIR}

ENTRYPOINT [ "/docker-entrypoint.sh" ]
#CMD [ "sleep", "infinity" ]
CMD [ "code-server", "serve-local", "--accept-server-license-terms", "--host", "0.0.0.0" ]
